"""The committed icon assets.

These files are generated by packaging/make_icon.py and committed, so the build
never depends on Pillow. That makes them worth guarding: a truncated or
mis-shaped icon is the kind of thing nobody notices until the taskbar looks
wrong. Nothing here imports Pillow - the formats are read directly.
"""

import struct
import unittest

from measurelog import config

EXPECTED_SIZES = {16, 24, 32, 48, 64, 128, 256}
PNG_MAGIC = b"\x89PNG\r\n\x1a\n"


def read_ico(data: bytes):
    reserved, kind, count = struct.unpack("<HHH", data[:6])
    entries = []
    for index in range(count):
        block = data[6 + 16 * index:22 + 16 * index]
        width, height, colours, pad, planes, bpp, size, offset = struct.unpack(
            "<BBBBHHII", block)
        entries.append({
            "width": width or 256, "height": height or 256, "bpp": bpp,
            "size": size, "offset": offset,
            "payload": data[offset:offset + size],
        })
    return reserved, kind, entries


class IconFileTests(unittest.TestCase):
    def setUp(self):
        self.ico_path = config.resource_path("icon.ico")
        self.png_path = config.resource_path("icon.png")

    def test_both_assets_are_found(self):
        self.assertIsNotNone(self.ico_path, "icon.ico is missing")
        self.assertIsNotNone(self.png_path, "icon.png is missing")

    def test_the_ico_header_is_well_formed(self):
        reserved, kind, entries = read_ico(self.ico_path.read_bytes())
        self.assertEqual(reserved, 0)
        self.assertEqual(kind, 1)           # 1 = icon, 2 = cursor
        self.assertTrue(entries)

    def test_the_ico_carries_the_sizes_windows_asks_for(self):
        _, _, entries = read_ico(self.ico_path.read_bytes())
        sizes = {entry["width"] for entry in entries}
        self.assertEqual(sizes, EXPECTED_SIZES)
        for needed in (16, 32, 256):        # taskbar, title bar, Explorer tiles
            self.assertIn(needed, sizes)

    def test_every_entry_is_a_complete_image(self):
        data = self.ico_path.read_bytes()
        _, _, entries = read_ico(data)
        for entry in entries:
            with self.subTest(size=entry["width"]):
                self.assertEqual(len(entry["payload"]), entry["size"],
                                 "entry is truncated")
                self.assertTrue(entry["payload"].startswith(PNG_MAGIC))
                self.assertEqual(entry["bpp"], 32)
                self.assertLessEqual(entry["offset"] + entry["size"], len(data))

    def test_entries_are_square(self):
        _, _, entries = read_ico(self.ico_path.read_bytes())
        for entry in entries:
            self.assertEqual(entry["width"], entry["height"])

    def test_the_png_is_a_256_square(self):
        data = self.png_path.read_bytes()
        self.assertTrue(data.startswith(PNG_MAGIC))
        # IHDR is always the first chunk: length, type, then width and height.
        width, height = struct.unpack(">II", data[16:24])
        self.assertEqual((width, height), (256, 256))

    def test_the_png_has_an_alpha_channel(self):
        # Colour type 6 is RGBA; the tile's rounded corners need transparency.
        data = self.png_path.read_bytes()
        self.assertEqual(data[25], 6)


if __name__ == "__main__":
    unittest.main()
